name: barber-shop
services:
  postgres:
    image: postgres:16-alpine
    container_name: barbershop-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - barbershop

  redis:
    image: redis:7-alpine
    container_name: barbershop-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - barbershop

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: barbershop-api
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - barbershop

networks:
  barbershop:
    driver: bridge

volumes:
  postgres_data:
  redis_data: